modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Mr-Pineapple/AdditionalGuns/issues"

[[mods]]
    modId="additionalguns"
    version="0.6.1"
    displayName="Additional Guns"
    updateJSONURL="https://raw.githubusercontent.com/Mr-Pineapple/ModUpdateJSON/master/additionalguns/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-guns"
    authors="Mr. Pineapple, Autovw"
    credits="ThatAvocado_Boi, JamesTheMaker, JaMychal1, SirSpark1313, VIKTORWOOD, Mercuriousity, Stabilizer, CasualNoLifer, Igggosha, W1therFl1nt343, Joel McCassidy"
    description="A community addon pack for MrCrayfish's Gun Mod - To contribute, head over the GitHub or simply join discord.gg/mrcrayfish and let us know!"

[[dependencies.additionalguns]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionalguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionalguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionalguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.3,)"
    ordering="NONE"
    side="BOTH"

[modproperties.additionalguns]
    catalogueItemIcon="additionalguns:ace_of_spades"
    configuredBackground="minecraft:textures/block/stripped_birch_log.png"
